# Generated by Django 5.2.10 on 2026-01-21 06:49

import apps.todolist.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('uid', models.CharField(default=apps.todolist.models.generate_uid, editable=False, max_length=22, unique=True, verbose_name='UID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='名称')),
                ('sort_order', models.FloatField(default=apps.todolist.models.get_timestamp_sortorder, verbose_name='排序')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='设置')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='附件列表，存储附件元信息的字典列表', verbose_name='附件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '清单分组',
                'verbose_name_plural': '清单分组',
                'db_table': 'todolist_groups',
                'ordering': ['sort_order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('uid', models.CharField(default=apps.todolist.models.generate_uid, editable=False, max_length=22, unique=True, verbose_name='UID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('sort_order', models.FloatField(default=apps.todolist.models.get_timestamp_sortorder, verbose_name='排序')),
                ('style', models.JSONField(blank=True, default=dict, help_text='颜色、图标等样式信息', verbose_name='样式')),
                ('view_type', models.CharField(choices=[('list', '列表视图'), ('card', '卡片视图')], default='list', max_length=16, verbose_name='视图类型')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='设置')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='附件列表，存储附件元信息的字典列表', verbose_name='附件')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='todolist.group', to_field='uid', verbose_name='所属分组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '待办项目',
                'verbose_name_plural': '待办项目',
                'db_table': 'todolist_projects',
                'ordering': ['sort_order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('uid', models.CharField(default=apps.todolist.models.generate_uid, editable=False, max_length=22, unique=True, verbose_name='uid')),
                ('name', models.CharField(help_text="标签名称，如'生活''工作'", max_length=50, verbose_name='名称')),
                ('color', models.CharField(default=apps.todolist.models.generate_tag_color, help_text='十六进制，如#ff0000', max_length=7, verbose_name='颜色')),
                ('sort_order', models.FloatField(default=0, verbose_name='排序')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'todolist_tags',
                'ordering': ['sort_order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('uid', models.CharField(default=apps.todolist.models.generate_uid, editable=False, max_length=22, unique=True, verbose_name='UID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='标题')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('status', models.IntegerField(choices=[(0, '待分配'), (1, '待办'), (2, '已完成'), (3, '已放弃')], db_index=True, default=1, verbose_name='状态')),
                ('priority', models.IntegerField(choices=[(0, '低'), (1, '中'), (2, '高'), (3, '紧急')], default=1, verbose_name='优先级')),
                ('sort_order', models.FloatField(default=apps.todolist.models.get_timestamp_sortorder, verbose_name='排序')),
                ('custom_group', models.CharField(blank=True, max_length=255, null=True, verbose_name='自定义分组')),
                ('is_all_day', models.BooleanField(default=True, verbose_name='全天任务')),
                ('start_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='开始时间')),
                ('due_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='截止时间')),
                ('completed_time', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='完成时间')),
                ('time_zone', models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='时区')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='附件列表，存储附件元信息的字典列表', verbose_name='附件')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todolist.task', to_field='uid', verbose_name='父任务')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todolist.project', to_field='uid', verbose_name='所属项目')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='todolist.tag', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '待办事项',
                'verbose_name_plural': '待办事项',
                'db_table': 'todolist_tasks',
                'ordering': ['sort_order', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('action', models.CharField(choices=[('created', '创建'), ('updated', '更新'), ('status_changed', '状态变更'), ('completed', '完成'), ('deleted', '删除')], max_length=64, verbose_name='操作类型')),
                ('detail', models.TextField(blank=True, verbose_name='详细信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='todolist.project', to_field='uid', verbose_name='项目')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='todolist.task', to_field='uid', verbose_name='任务')),
            ],
            options={
                'verbose_name': '活动日志',
                'verbose_name_plural': '活动日志',
                'db_table': 'todolist_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['user', '-updated_at'], name='group_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['user', 'name'], name='group_user_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'user')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', '-updated_at'], name='project_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user', 'group'], name='project_user_group_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'group', 'user')},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', '-updated_at'], name='tag_user_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['user', 'name'], name='tag_user_name_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'user')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'status', '-updated_at'], name='task_user_status_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'project', '-updated_at'], name='task_user_project_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'due_date'], name='task_user_due_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['user', 'start_date'], name='task_user_start_date_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='activity_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['task', '-created_at'], name='activity_task_created_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['project', '-created_at'], name='activity_project_created_idx'),
        ),
    ]
