# Generated by Django 5.2.10 on 2026-01-21 10:50

import apps.todolist.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskView',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('uid', models.CharField(default=apps.todolist.models.generate_uid, editable=False, max_length=22, unique=True, verbose_name='UID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='视图名称')),
                ('view_type', models.CharField(choices=[('list', '列表视图'), ('board', '看板视图'), ('calendar', '日历视图'), ('table', '表格视图')], default='list', max_length=16, verbose_name='视图类型')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认视图')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('sort_order', models.FloatField(default=apps.todolist.models.get_timestamp_sortorder, verbose_name='排序')),
                ('filters', models.JSONField(blank=True, default=list, help_text='筛选规则列表，格式：[{field, operator, value, logic}]', verbose_name='筛选条件')),
                ('sorts', models.JSONField(blank=True, default=list, help_text='排序规则列表，格式：[{field, direction}]', verbose_name='排序规则')),
                ('group_by', models.CharField(blank=True, help_text='按哪个字段分组显示', max_length=50, null=True, verbose_name='分组字段')),
                ('display_settings', models.JSONField(blank=True, default=dict, help_text='列显示、颜色、图标等设置', verbose_name='显示设置')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='todolist.project', to_field='uid', verbose_name='所属项目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '任务视图',
                'verbose_name_plural': '任务视图',
                'db_table': 'ct_task_views',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['user', 'project', 'sort_order'], name='view_user_project_sort_idx'), models.Index(fields=['user', 'is_default'], name='view_user_default_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'project', 'name'), name='unique_view_name_per_project')],
            },
        ),
    ]
