# Generated by Django 5.2.10 on 2026-01-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='附件列表，存储附件ID的列表', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='project',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='附件列表，存储附件ID的列表', verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='附件列表，存储附件ID的列表', verbose_name='附件'),
        ),
    ]
