# Generated by Django 5.2.10 on 2026-01-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_group_attachments_alter_project_attachments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='project',
            name='attachments',
        ),
    ]
