# Generated by Django 5.2.10 on 2026-02-12 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_make_project_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='todolist.project', to_field='uid', verbose_name='项目'),
        ),
    ]
