# Generated by Django 5.2.10 on 2026-02-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_allow_null_project_in_activity_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskview',
            name='is_system',
            field=models.BooleanField(default=False, help_text='系统视图用于初始化新用户', verbose_name='是否系统视图'),
        ),
    ]
