# Generated by Django 5.2.10 on 2026-02-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_add_is_system_field_to_taskview'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskview',
            name='follow_selected_project',
            field=models.BooleanField(default=True, help_text='True: 跟随主界面所选清单过滤; False: 使用视图固定的所属清单', verbose_name='跟随所选清单'),
        ),
    ]
