# Generated by Django 5.2.10 on 2026-03-30 08:00

import apps.todolist.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_add_follow_selected_project_to_taskview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskview',
            name='display_settings',
        ),
        migrations.AddField(
            model_name='taskview',
            name='view_settings',
            field=models.JSONField(blank=True, default=dict, help_text='视图级别配置，非卡片级别', verbose_name='视图设置'),
        ),
        migrations.AlterField(
            model_name='taskview',
            name='view_type',
            field=models.CharField(choices=[('list', '列表视图'), ('board', '看板视图'), ('calendar', '日历视图'), ('table', '表格视图'), ('timeline', '时间线视图'), ('gallery', '画廊视图')], default='list', max_length=16, verbose_name='视图类型'),
        ),
        migrations.CreateModel(
            name='TaskCardConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('uid', models.CharField(default=apps.todolist.models.generate_uid, editable=False, max_length=22, unique=True, verbose_name='UID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_preset', models.BooleanField(default=False, verbose_name='系统预设')),
                ('layout', models.CharField(choices=[('compact', '紧凑'), ('comfortable', '舒适'), ('spacious', '宽松')], default='comfortable', max_length=20, verbose_name='布局密度')),
                ('style', models.JSONField(blank=True, default=dict, help_text='borderRadius, shadow, padding, hoverEffect, checkboxStyle 等', verbose_name='卡片样式')),
                ('field_configs', models.JSONField(blank=True, default=list, help_text='有序列表: [{field, visible, position, style}]', verbose_name='字段配置')),
                ('sort_order', models.FloatField(default=apps.todolist.models.get_timestamp_sortorder, verbose_name='排序')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '卡片配置',
                'verbose_name_plural': '卡片配置',
                'db_table': 'ct_card_configs',
                'ordering': ['is_preset', 'sort_order', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='taskview',
            name='card_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='todolist.taskcardconfig', to_field='uid', verbose_name='卡片配置'),
        ),
        migrations.AddIndex(
            model_name='taskcardconfig',
            index=models.Index(fields=['user', '-updated_at'], name='cardcfg_user_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskcardconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'name'), name='unique_card_config_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='taskcardconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_preset', True)), fields=('name',), name='unique_preset_card_config_name'),
        ),
    ]
